version: '3'

services:
     web:
       image: nginx:alpine
       ports:
           - "8080:80"
       volumes:
           - ././src:/anakin/
           - ./conf.d:/etc/nginx/conf.d
       depends_on:
           - php
       networks:
           - nginxphp

     php:
       build: 
         context: ./tools/Docker
         dockerfile: Dockerfile  
       volumes:
           - ./src:/anakin
       expose:
           - 9000
       depends_on:
           - memcached
       networks:
           - nginxphp

     memcached:
       image: bitnami/memcached:latest
       ports:
           - "11211:11211"
       networks:
           - nginxphp           

networks:
     nginxphp: